# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df5bfd362ae400b400d79af9bc419e988c72e7a2df7aebc541137d2f27e125bb93b09d877ecc0cae931a9b8c16ef96f1c7329a8b2d788eadf3a0f5cc9bb4d4e7

test:
  secret_key_base: 91a21b8af0492c5893228989638a977f5e7cf895e0a94a3a0cd34976a4582b84e68c4e940e3369f2297218eaebf4bce2cc07441512a9c2d645734c20e08024b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
